server:
  port: 8083
  servlet:
    context-path: /

spring:
  application:
    name: fc-configsupplier
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  cloud:
    function:
      definition: configSupplier
      scan:
        packages: com.fc.serverless.configsupplier
      web:
        export:
          enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
# Logging
logging:
  level:
    com.fc: DEBUG
    org.springframework.cloud.function: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: OFF
    root: WARN