server:
  port: 8081
  servlet:
    context-path: /

spring:
  cloud:
    function:
      definition: function1,low,sup
      scan:
        packages: com.fc.serverless.sample.function1

function2:
  url: http://localhost:8082/function2

logging:
  level:
    org.springframework.cloud.function: DEBUG
    com.fc.serverless: DEBUG