server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: fc-orderprocessor
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  cloud:
    function:
      definition: orderProcessor
      scan:
        packages: com.fc.serverless.orderprocessor
      web:
        export:
          enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
# Remote function URLs for cross-service calls
fc:
  functions:
    priceCalculator:
      url: ${FC_LAMBDA_URL_PRICECALCULATOR:http://localhost:8082/priceCalculator}
      authType: ${FC_AUTH_TYPE_PRICECALCULATOR:AWS_IAM}

# Logging
logging:
  level:
    com.fc: DEBUG
    org.springframework.cloud.function: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: OFF
    root: WARN