server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: fc-orderprocessor
    banner-mode: off
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  cloud:
    function:
      definition: orderProcessor,sup
      scan:
        packages: com.fc.serverless.orderprocessor

userValidator:
  url: localhost:8082/userValidator

inventoryChecker:
  url: localhost:8083/inventoryChecker

paymentProcessor:
  url: localhost:8084/paymentProcessor

# Logging
logging:
  level:
    com.fdd: DEBUG
    com.fdd.aws.lambda: DEBUG
    com.fdd.lambda.orderprocessor: DEBUG
    org.springframework.security: OFF  # ❌ Turn off security logging
    root: WARN