server:
  port: 8082
  servlet:
    context-path: /

spring:
  application:
    name: fdd-uservalidator
    banner-mode: off
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  cloud:
    function:
      definition: userValidator,sup
      scan:
        packages: com.fc.serverless.uservalidator

# Logging
logging:
  level:
    com.fdd: DEBUG
    com.fdd.aws.lambda: DEBUG
    com.fdd.lambda.orderprocessor: DEBUG
    org.springframework.security: OFF  # ❌ Turn off security logging
    root: WARN