server:
  port: 8082
  servlet:
    context-path: /

spring:
  cloud:
    function:
      definition: function2,low2,sup2
      scan:
        packages: com.fc.serverless.sample.function2

logging:
  level:
    org.springframework.cloud.function: DEBUG
    com.fc.serverless: DEBUG