server:
  port: ${PORT:8081}
  servlet:
    context-path: /

spring:
  application:
    name: fc-orderprocessor
  main:
    web-application-type: servlet
    allow-bean-definition-overriding: true
    lazy-initialization: ${LAMBDA_MODE:false}
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
      - org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  cloud:
    function:
      definition: orderProcessor
      scan:
        packages: com.fc.serverless.orderprocessor
      web:
        export:
          enabled: true
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false

# ENHANCED FC Framework Configuration with Auth Types
fc:
  functions:
    # PriceCalculator - IAM protected
    priceCalculator:
      url: ${FC_LAMBDA_URL_PRICECALCULATOR:http://localhost:8085/priceCalculator}
      authType: ${FC_AUTH_PRICECALCULATOR:AWS_IAM}

# Environment detection
environment:
  type: ${ENVIRONMENT_TYPE:local}
  lambda: ${AWS_LAMBDA_FUNCTION_NAME:#{null}}

# Enhanced Logging with Apache Commons Logging
logging:
  level:
    com.fc: ${LOG_LEVEL:INFO}
    com.fc.serverless.auth: DEBUG
    com.fc.serverless.proxy: DEBUG
    org.springframework.cloud.function: WARN
    org.springframework.web: WARN
    org.springframework.security: OFF
    root: ${ROOT_LOG_LEVEL:WARN}
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"